[project]
name = "synthia"
version = "0.1.0"
description = "Machine learning network created for the 2024 DeepView competition"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyqt5>=5.15.11",
    "pyqt5-qt5==5.15.2",
    "tensorflow>=2.18.0",
]
